#!/bin/bash

# VizStack - A Framework to manage visualization resources

# Copyright (C) 2009-2010 Hewlett-Packard
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

nodes=$1
all_nodes=$*
VERSION=0.3-0
vizrpm=vizstack-${VERSION}.x86_64.rpm
osgdemosrpm=vizstack-opensg-demos-${VERSION}.x86_64.rpm

if test -f /usr/src/redhat/RPMS/x86_64/$vizrpm; then
    # RHEL path
    filepath=/usr/src/redhat/RPMS/x86_64/
else
    # SLES path
    filepath=/usr/src/packages/RPMS/x86_64/
fi

cd /tmp # get rid of "directory unknown" kind of errors
for node in $all_nodes; do
	echo ""
	echo "Processing $node"
	echo ""
#	scp /usr/src/redhat/RPMS/x86_64/$vizrpm $node:/tmp
	scp $filepath/$vizrpm $node:/tmp
	echo "Removing VizStack RPM"
	srun -w $node rpm -e vizstack
	echo "Installing VizStack RPM"
	srun -w $node rpm -ivh /tmp/$vizrpm

	scp $filepath/$osgdemosrpm $node:/tmp
	echo "Removing OpenSG Demos RPM"
	srun -w $node rpm -e vizstack-opensg-demos
	echo "Installing OpenSG Demos RPM"
	srun -w $node rpm -ivh /tmp/$osgdemosrpm
done
