#!/usr/bin/env python

#
# local-combined-desktop 
#
# Sample script that shows how to combine two displays on a 
# single node.
#
# Consider the following case :
# - You have 4 GPUs
# - You want to drive a 3x2 desktop tiled display using these,
#   and you want it controllable using a keyboard and
#   mouse
#
# VizStack's tiled display model does not drectly support this.
#
# So how would you make this possible ?
#
# 1. Create two tiled displays
#    - first tiled display with two GPUs, each driving two
#      displays. This gives you a 2x2 tiled display. Include
#      a keyboard and mouse in this tiled display.
#    - create a second tiled display, with each driving one
#      display device. This gives you a 1x2 tiled display. Do
#      not include a keyboard and a mouse with this tiled display.
#    - use the same resolution on both the tiled displays
#
# 2. Start off with the viz-desktop script as a base. Modify it to
#      - allocate both tiled displays
#      - add the screens of the X server of the right TD to the
#        X server on the left TD.
#      - add the right bezels on the left TD and the
#        left bezels on the right TD
#      - note that display rotation complicates the screen 
#        combination logic, so we don't handle it :-)
#

# VizStack - A Framework to manage visualization resources

# Copyright (C) 2009-2010 Hewlett-Packard
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.


"""
viz_desktop

Starts a desktop for a user on a tiled display, with keyboard and mouse enabled.
"""
import vsapi
from vsapi import ResourceAccess, Screen, GPU, Server, Keyboard, Mouse, VizResource, VizError
from pprint import pprint
from optparse import OptionParser, OptionGroup
import sys
import re
import time
import string
import socket
import os
import vsutil

def isTDSuitable(tdToUse):
	"""
	Ensure that the tiled display meets our requirements !
	
	0. The resource group must be a tiled_display
	1. Must have _exactly_ one reslist.
	2. The reslist must have at least one real server [this is enusred by the SSM]
	3. The reslist must have one keyboard
	4. The reslist must have one mouse
	5. The reslist must atleast one GPU [this is ensure by the SSM]
	"""
	if tdToUse.getType()!="tiled_display":
		msg = "Resource group '%s' has handler '%s'. Only tiled_displays are supported by this script"%(tdToUse.getType())
		return (False, msg)

	tdToUse = vsutil.normalizeRG(tdToUse)

	tdRes = tdToUse.getResources()
	if len(tdRes)!=1:
		msg =  "The passed tiled_display '%s' is not suitable for this script. It needs to define resources on one node using exactly one X server. '%s' has %d reslists."%(tdToUse.getName(), tdToUse.getName(), len(tdRes))
		return (False, msg)

	# Ensure resources are on one host.
	hosts = map(lambda x: x.getHostName(), tdRes[0])
	hostsUniq = {}
	for name in hosts:
		hostsUniq[name] = None
	hostsUniq = hostsUniq.keys()
	if len(hostsUniq)>1:
		msg =  "The passed tiled_display '%s' is not suitable for this script. It needs to define resources on exactly one node. '%s' has resources defined on %d node(s): %s."%(tdToUse.getName(), tdToUse.getName(), len(hostsUniq), hostsUniq)
		return (False, msg)

	kbd = vsapi.extractObjects(Keyboard, tdRes)
	if len(kbd)!=1:
		msg = "Tiled display needs to use exactly one keyboard. You're using %d"%(len(kbd))
		return (False, msg)

	mouse = vsapi.extractObjects(Mouse, tdRes)
	if len(mouse)!=1:
		msg = "Tiled display needs to use exactly one mouse. You're using %d"%(len(mouse))
		return (False, msg)

	return (True, "")

#
# Script body starts from here.
#
if __name__ == "__main__":
	# Parse and validate options
	parser = OptionParser(description=
"""Starts a desktop session for a user on a tiled display, with keyboard and mouse enabled.

You can use tiled displays which use resources only from a single node with this script.
""")
	group = OptionGroup(parser, "Frequently used options")
	group.add_option("-t", "--tiled-display-prefix", action="store", type="string", dest="tiled_display_prefix", help="The tiled display prefix to use for the desktop. The tiled displays prefix-LEFT and prefix-RIGHT are allocated by this script")
	group.add_option("-B", "--enable-bezels", dest="enable_bezels", action="store_true", default=False, help="Enable bezel compensation by configuring invisible pixels in the areas of the monitor bezels. This option has no effect when projectors are used to drive the desktop. By default, you get a continuous desktop with no hidden pixels.")
	group.add_option("-m", "--display-mode", dest="display_mode", help="The mode in which to run all the displays in.")
	parser.add_option_group(group)
	group = OptionGroup(parser, "Additional options")
	group.add_option("--no-framelock", action="store_true", dest="disable_framelock", default=False, help="VizStack sets up framelock if this is enabled in the configuration of the used tiled display. Framelock provides hardware synchronization of all the displays in the Tiled Display. If your framelock chain or tiled display is not setup properly for framelock, then your desktop will not be started. Use this option if framelock setup fails, but you want to use the tiled display without framelock")
	group.add_option("--show-usable-modes", dest="show_usable_modes", action="store_true", default=False, help="Prints out the usable modes that can be used with the requested tiled display.")
	group.add_option("--show-usable-tiled-displays", dest="show_usable_tiled_displays", action="store_true", default=False, help="Prints out the names of the Tiled Displays that can be used with this script.")
	group.add_option("-a", "--allocate-from", dest="allocate_from", action="append", help="Allocate the tiled display on this hostname. If you use this option multiple times, then a single tiled display from one of the specified hosts will be used. Note that the allocation is independent of the order in which the hostnames are specified on the command line.")
	parser.add_option_group(group)
	(options, args) = parser.parse_args(sys.argv[1:])

	# Extra arguments are errors.
	if len(args)>0:
		print >>sys.stderr # empty line
		print >>sys.stderr, "Invalid argument(s) on command line : %s"%(string.join(args,","))
		print >>sys.stderr # empty line
		parser.print_help()
		sys.exit(-1)

	# Name of tiled display must be specified
	if (options.tiled_display_prefix is None) and (options.show_usable_tiled_displays is False):
		print >>sys.stderr, "You need to specify a tiled display prefix"
		parser.print_help()
		sys.exit(-1)

	# Connect to the SSM
	try:
		ra = ResourceAccess()
	except VizError, e:
		print >>sys.stderr, "%s"%(str(e))
		sys.exit(-1)

	# Validate the host list if user asked for specific hosts
	# This helps us print messages that make more sense for the
	# user
	if options.allocate_from is not None:
		# Get a list of all hostnames from the SSM
		nodeList = ra.queryResources(vsapi.VizNode())
		validHostList = []
		for node in nodeList:
		        validHostList.append(node.getHostName())

		# Find out what's not valid
		invalidHostNames = filter(lambda x: x not in validHostList, options.allocate_from)

		# And print them out
		if len(invalidHostNames)>0:
			print >>sys.stderr
			print >>sys.stderr, "The following hostname(s) specified on the command line are invalid\n%s"%(invalidHostNames)
			print >>sys.stderr
			print >>sys.stderr, "Please ensure that they are indeed part of this system."
			print >>sys.stderr
			sys.exit(-1)

	if options.show_usable_tiled_displays:
		allTDs = ra.queryResources(vsapi.ResourceGroup())
		suitableTDs = filter(lambda x: isTDSuitable(x)[0], allTDs)
		if len(suitableTDs)>0:
			print "The following tiled displays can be used with this script:"
			for td in suitableTDs:
				print td.getName()
			sys.exit(0)
		else:
			print >>sys.stderr, "None of the defined tiled displays can be used with this script"
			sys.exit(-1)

	leftTD = options.tiled_display_prefix + '-LEFT'
	rightTD = options.tiled_display_prefix + '-RIGHT'

	# Ensure that the left Tiled Display is defined
	tdMatch = ra.queryResources(vsapi.ResourceGroup(leftTD))
	if len(tdMatch)==0:
		print >>sys.stderr, "Tiled Display '%s' does not exist."%(leftTD)
		sys.exit(-1)

	tdToUse_left = tdMatch[0]

	# Ensure that the right Tiled Display is defined
	tdMatch = ra.queryResources(vsapi.ResourceGroup(rightTD))
	if len(tdMatch)==0:
		print >>sys.stderr, "Tiled Display '%s' does not exist."%(rightTD)
		sys.exit(-1)

	tdToUse_right = tdMatch[0]

	# Retrieve a list of modes valid for the display device used
	displayModes = []
	rg = tdToUse_left.getHandlerObject()
	ddName = rg.getParam('display_device')
	ddList = ra.getTemplates(vsapi.DisplayDevice(ddName))
	dd = ddList[0]
	displayModes = dd.getAllModes()

	# Show list of valid modes if the user requested for it
	if options.show_usable_modes:
		print "Modes usable with tiled display '%s' are:"%(tdToUse.getName())
		for mode in dd.getAllModes():
			print mode['alias']
		sys.exit(0)

	# Validate user provided mode
	if options.display_mode is not None:
		allAliases = map(lambda x: x['alias'], dd.getAllModes())
		if options.display_mode not in allAliases:
			print >>sys.stderr, "Invalid display mode '%s'"%(options.display_mode)
			sys.exit(-1)

	# Allocate resources needed for the desktop
	try:
		if options.allocate_from is None:
			potentialHostList = []
		else:
			potentialHostList = options.allocate_from

		# Allocate the tiled display
		alloc = ra.allocate([
			  tdToUse_left, tdToUse_right
		        ],
		        potentialHostList
		)
	except vsapi.VizError, e:
		print >>sys.stderr, "Unable to allocate resources needed for the desktop session."
		print >>sys.stderr, "Reason: %s"%(str(e))
		print >>sys.stderr
		print >>sys.stderr, "Please try again later"
		sys.exit(-1)

	# If the user wants to use a different mode, then customize it now
	res = alloc.getResources()
	tdInUse_left = res[0].getHandlerObject()
	tdInUse_right = res[1].getHandlerObject()

	# Enable desktop bezels. This will ensure that running applications will
	# skip over bezels in the right way!
	if options.enable_bezels:
		tdInUse_left.setParam('bezels', 'desktop')
		tdInUse_right.setParam('bezels', 'desktop')
	else:
		tdInUse_left.setParam('bezels', 'disable')
		tdInUse_right.setParam('bezels', 'disable')

	if options.display_mode is None:
		options.display_mode = tdInUse_left.getParam('display_mode')

	# Set the same display device and mode on both tiled displays
	tdInUse_left.setParam('display_device', ddName)
	tdInUse_right.setParam('display_device', ddName)
	tdInUse_left.setParam('display_mode', options.display_mode)
	tdInUse_right.setParam('display_mode', options.display_mode)
			
	# Propagate the X server settings to the SSM
	try:
		alloc.setupViz(ra)
	except ValueError, e:
		print >>sys.stderr, "Failed to setup tiled display. Reason :%s"%(str(e))
		# Deallocate resources.
		ra.deallocate(alloc)
		# Disconnect from the SSM - we're done!
		ra.stop()
		sys.exit(-1)

	# Now, modify the servers
	leftServer = vsapi.extractObjects(vsapi.Server, res[0].getResources())[0]
	rightServer = vsapi.extractObjects(vsapi.Server, res[1].getResources())[0]

	ltd = tdInUse_left.getActualLayoutMatrix()
	rtd = tdInUse_right.getActualLayoutMatrix()

	if options.enable_bezels:
		leftBezel = dd.getModeByAlias(options.display_mode)['bezel']['left']
		rightBezel = dd.getModeByAlias(options.display_mode)['bezel']['right']
	else:
		leftBezel = rightBezel = 0

	# Include a right bezel on the leftmost screens
	ltd_last_col = len(ltd[0])-1
	for ltd_row in ltd:
		bl = ltd_row[ltd_last_col]
		scr = bl['screen']
		resolution = scr.getFBProperty('resolution')
		scr.setFBProperty('resolution', [resolution[0]+rightBezel, resolution[1]])

	# Compensate for left & right bezel on all screens consittuting column 0 on the right tiled display
	# Shift the other screen positions by this much
	# Add each screen on the right server to the left server
	rtd_shift = ltd[0][ltd_last_col]['rect_area'][2]
	rtd_screen_offset = len(ltd)*len(ltd[0])
	for rtd_row in rtd:
		for col_index in range(len(rtd_row)):
			bl = rtd_row[col_index]
			scr = bl['screen']
			resolution = scr.getFBProperty('resolution')
			try:
				position = scr.getFBProperty('position')
			except:
				# Some simple TDs may not have position set, so...
				position = [0,0]
			if col_index == 0:
				scr.setFBProperty('resolution', [resolution[0]+leftBezel+rightBezel, resolution[1]])
				scr.setFBProperty('position', [position[0]+rtd_shift, position[1]])
				for gpu in bl['gpus']:
					gpuScanouts = gpu.getScanouts()
					for pi in gpuScanouts:
						thisScanout = gpuScanouts[pi]
						newX = thisScanout['area_x']+leftBezel+rightBezel
						gpu.setScanout(pi, display_device = thisScanout['display_device'], mode = thisScanout['mode'], outputX = newX, outputY = thisScanout['area_y'])
			else:
				scr.setFBProperty('position', [position[0]+rtd_shift+leftBezel+rightBezel, position[1]])
			scr.setScreenNumber(scr.getScreenNumber()+rtd_screen_offset)
			leftServer.addScreen(scr)

	# Enable Xinerama so that the whole desktop looks like a single large one !
	leftServer.combineScreens(True)

	rightServer.clearConfig()

	ra.updateServerConfig(alloc.getId(), [leftServer, rightServer])

	print "Starting Desktop for user on Tiled Display '%s' and '%s'"%(leftTD, rightTD)

	try:
		# Get the first GPU
		gpu0 = vsapi.extractObjects(GPU, res[0].getResources())[0]
		sched = gpu0.getSchedulable()
		# Use startx to start the desktop session.
		# Use the "-disablexineramaextension" option to ensure the desktop spans all GPUs if Xinerama is enabled.
		proc = sched.run(["startx", "--", "/usr/X11R6/bin/vs-X", leftServer.getDISPLAY(), "-disablexineramaextension", "-logverbose", "6"], outFile=open("/dev/null","w"), errFile=open("/dev/null","w"))

		# Wait for the X servers, default timeout. Note that the right server is not used, so we neither start it nor we use it
		ra.waitXState(alloc, 1, serverList=[leftServer])

		# Enable framelock if it is possible and not explicitly disabled
		resList = alloc.getResources()
		rg = resList[0]
		td = rg.getHandlerObject()
		if td.getParam('framelock') and (not options.disable_framelock):
			if not vsutil.isFrameLockAvailable(resList):
				print >>sys.stderr, "ERROR: Framelock is not available for this tiled display. Exiting..."
				sys.exit(1)	
			print "Enabling Frame Lock..."
			try:
				vsutil.enableFrameLock(resList)
				print "Frame Lock setup successful."
			except VizError, e:
				print >>sys.stderr, "Exiting due to failure to enable frame lock. Reason: %s"%(str(e))
				sys.exit(1)
		print 
		print "NOTE: The X server will be stopped and the resources"
		print "will be cleaned up when you logout from the desktop"
		print 
		print "Pressing ^C does the job too..."
		print 

		# Wait for exit
		proc.wait()
	except KeyboardInterrupt, e:
		pass

	# Stop the real X server
	alloc.stopViz(ra)

	# Deallocate resources.
	ra.deallocate(alloc)

	# Disconnect from the SSM - we're done!
	ra.stop()
