ALL : viz-avizovr.1 viz-rgs.1 viz-tvnc.1 viz-vgl.1 viz-paraview.1
	echo "Done building man pages"

viz-avizovr.1 : viz-avizovr.txt
	a2x -f manpage -d manpage viz-avizovr.txt

viz-rgs.1 : viz-rgs.txt
	a2x -f manpage -d manpage viz-rgs.txt

viz-tvnc.1 : viz-tvnc.txt
	a2x -f manpage -d manpage viz-tvnc.txt

viz-vgl.1 : viz-vgl.txt
	a2x -f manpage -d manpage viz-vgl.txt

viz-paraview.1 : viz-paraview.txt
	a2x -f manpage -d manpage viz-paraview.txt
